
BugGrabberDB = {
	["session"] = 16,
	["lastSanitation"] = 3,
	["errors"] = {
		{
			["message"] = "...\\SkeenCore3GUISpellFlash\\SkeenCore3GUISpellFlash-v1.1.4.lua:53: attempt to index upvalue \"GUI\" (a nil value)",
			["time"] = "2013/09/20 11:30:46",
			["locals"] = "self = <table> {\n ActivateGUI = <func> @..\\SkeenCore3GUI.lua:41\n SetUpdateInterval = <func> @..\\SkeenCore3Options.lua:106\n GetScale = <func> @..\\SkeenCore3Options.lua:93\n options = SkeenCore3OptionFrame {}\n RegisterDisabledGUI = <func> @..\\SkeenCore3GUIDisabled.lua:6\n LoadModules = <func> @..\\SkeenCore3Modules.lua:79\n option_frame_name = \"SkeenCore3OptionFrame\"\n HandlePluginOptionsFrame = <func> @..\\SkeenCore3Modules.lua:22\n displayFrame = <unnamed> {}\n CreateOptionFrame = <func> @..\\SkeenCore3Options.lua:6\n PrepareSkeenCore3Database = <func> @..\\SkeenCore3.lua:47\n CreateSlashCommands = <func> @..\\SkeenCore3Slash.lua:11\n ProcessCooldowns = <func> @..\\SkeenCore3.lua:69\n UpdateActiveGUI = <func> @..\\SkeenCore3GUI.lua:29\n SetScale = <func> @..\\SkeenCore3Options.lua:97\n GetLocked = <func> @..\\SkeenCore3Options.lua:84\n RotationUpdate = <func> @..\\SkeenCore3.lua:95\n LoadGUIs = <func> @..\\SkeenCore3GUI.lua:70\n SlashCommandList = <func> @..\\SkeenCore3Slash.lua:60\n UpdateDragability = <func> @..\\SkeenCore3Frame.lua:25\n ToggleLocked = <func> @..\\SkeenCore3Options.lua:88\n GetUpdateInterval = <func> @..\\SkeenCore3Options.lua:102\n CreateGUI = <func> @..\\SkeenCore3Frame.lua:4\n events = <table> {}\n PrepareSkeenCore3Active = <func> @..\\SkeenCore3.lua:19\n UpdateActiveModule = <func> @..\\SkeenCore3Modules.lua:43\n HandleGUIOptionsFrame = <func> @..\\SkeenCore3GUI.lua:8\n GetFirstGUI = <func> @..\\SkeenCore3GUI.lua:85\n eventHandler = <unnamed> {}\n}\nspells = <table> {\n current = 1126\n}\ncooldowns_pre = <table> {\n 1 = 5217\n 2 = 50334\n 3 = 106737\n}\ncooldowns = <table> {\n 1 = 5217\n 2 = 50334\n 3 = 106737\n}\nSkeenCore3 = <table> {\n ActivateGUI = <func> @..\\SkeenCore3GUI.lua:41\n SetUpdateInterval = <func> @..\\SkeenCore3Options.lua:106\n GetScale = <func> @..\\SkeenCore3Options.lua:93\n options = SkeenCore3OptionFrame {}\n RegisterDisabledGUI = <func> @..\\SkeenCore3GUIDisabled.lua:6\n LoadModules = <func> @..\\SkeenCore3Modules.lua:79\n option_frame_name = \"SkeenCore3OptionFrame\"\n HandlePluginOptionsFrame = <func> @..\\SkeenCore3Modules.lua:22\n displayFrame = <unnamed> {}\n CreateOptionFrame = <func> @..\\SkeenCore3Options.lua:6\n PrepareSkeenCore3Database = <func> @..\\SkeenCore3.lua:47\n CreateSlashCommands = <func> @..\\SkeenCore3Slash.lua:11\n ProcessCooldowns = <func> @..\\SkeenCore3.lua:69\n UpdateActiveGUI = <func> @..\\SkeenCore3GUI.lua:29\n SetScale = <func> @..\\SkeenCore3Options.lua:97\n GetLocked = <func> @..\\SkeenCore3Options.lua:84\n RotationUpdate = <func> @..\\SkeenCore3.lua:95\n LoadGUIs = <func> @..\\SkeenCore3GUI.lua:70\n SlashCommandList = <func> @..\\SkeenCore3Slash.lua:60\n UpdateDragability = <",
			["stack"] = "...\\SkeenCore3GUISpellFlash\\SkeenCore3GUISpellFlash-v1.1.4.lua:53: in function \"ShowGUI\"\nSkeenCore3\\SkeenCore3-1.10.0.5.lua:107: in function \"RotationUpdate\"\nSkeenCore3-1.10.0.5\\SkeenCore3Events.lua:72: in function <SkeenCore3\\SkeenCore3Events.lua:68>",
			["session"] = 3,
			["counter"] = 53,
		}, -- [1]
		{
			["message"] = "...\\SkeenCore3GUISpellFlash\\SkeenCore3GUISpellFlash-v1.1.4.lua:21: attempt to index upvalue \"GUI\" (a nil value)",
			["time"] = "2013/09/20 11:30:46",
			["locals"] = "self = <table> {\n ActivateGUI = <func> @..\\SkeenCore3GUI.lua:41\n SetUpdateInterval = <func> @..\\SkeenCore3Options.lua:106\n GetScale = <func> @..\\SkeenCore3Options.lua:93\n options = SkeenCore3OptionFrame {}\n RegisterDisabledGUI = <func> @..\\SkeenCore3GUIDisabled.lua:6\n LoadModules = <func> @..\\SkeenCore3Modules.lua:79\n option_frame_name = \"SkeenCore3OptionFrame\"\n HandlePluginOptionsFrame = <func> @..\\SkeenCore3Modules.lua:22\n displayFrame = <unnamed> {}\n CreateOptionFrame = <func> @..\\SkeenCore3Options.lua:6\n PrepareSkeenCore3Database = <func> @..\\SkeenCore3.lua:47\n CreateSlashCommands = <func> @..\\SkeenCore3Slash.lua:11\n ProcessCooldowns = <func> @..\\SkeenCore3.lua:69\n UpdateActiveGUI = <func> @..\\SkeenCore3GUI.lua:29\n SetScale = <func> @..\\SkeenCore3Options.lua:97\n GetLocked = <func> @..\\SkeenCore3Options.lua:84\n RotationUpdate = <func> @..\\SkeenCore3.lua:95\n LoadGUIs = <func> @..\\SkeenCore3GUI.lua:70\n SlashCommandList = <func> @..\\SkeenCore3Slash.lua:60\n UpdateDragability = <func> @..\\SkeenCore3Frame.lua:25\n ToggleLocked = <func> @..\\SkeenCore3Options.lua:88\n GetUpdateInterval = <func> @..\\SkeenCore3Options.lua:102\n CreateGUI = <func> @..\\SkeenCore3Frame.lua:4\n events = <table> {}\n PrepareSkeenCore3Active = <func> @..\\SkeenCore3.lua:19\n UpdateActiveModule = <func> @..\\SkeenCore3Modules.lua:43\n HandleGUIOptionsFrame = <func> @..\\SkeenCore3GUI.lua:8\n GetFirstGUI = <func> @..\\SkeenCore3GUI.lua:85\n eventHandler = <unnamed> {}\n}\nGUIName = \"SkeenCore3GUISpellFlash\"\nSkeenCore3 = <table> {\n ActivateGUI = <func> @..\\SkeenCore3GUI.lua:41\n SetUpdateInterval = <func> @..\\SkeenCore3Options.lua:106\n GetScale = <func> @..\\SkeenCore3Options.lua:93\n options = SkeenCore3OptionFrame {}\n RegisterDisabledGUI = <func> @..\\SkeenCore3GUIDisabled.lua:6\n LoadModules = <func> @..\\SkeenCore3Modules.lua:79\n option_frame_name = \"SkeenCore3OptionFrame\"\n HandlePluginOptionsFrame = <func> @..\\SkeenCore3Modules.lua:22\n displayFrame = <unnamed> {}\n CreateOptionFrame = <func> @..\\SkeenCore3Options.lua:6\n PrepareSkeenCore3Database = <func> @..\\SkeenCore3.lua:47\n CreateSlashCommands = <func> @..\\SkeenCore3Slash.lua:11\n ProcessCooldowns = <func> @..\\SkeenCore3.lua:69\n UpdateActiveGUI = <func> @..\\SkeenCore3GUI.lua:29\n SetScale = <func> @..\\SkeenCore3Options.lua:97\n GetLocked = <func> @..\\SkeenCore3Options.lua:84\n RotationUpdate = <func> @..\\SkeenCore3.lua:95\n LoadGUIs = <func> @..\\SkeenCore3GUI.lua:70\n SlashCommandList = <func> @..\\SkeenCore3Slash.lua:60\n UpdateDragability = <func> @..\\SkeenCore3Frame.lua:25\n ToggleLocked = <func> @Add",
			["stack"] = "...\\SkeenCore3GUISpellFlash\\SkeenCore3GUISpellFlash-v1.1.4.lua:21: in function \"CreateGUI\"\nSkeenCore3-1.10.0.5\\SkeenCore3GUI.lua:62: in function \"ActivateGUI\"\nSkeenCore3-1.10.0.5\\SkeenCore3GUI.lua:31: in function \"UpdateActiveGUI\"\nSkeenCore3-1.10.0.5\\SkeenCore3Options.lua:68: in function \"func\"\nFrameXML\\UIDropDownMenu.lua:710: in function \"UIDropDownMenuButton_OnClick\"\n<string>:\"*:OnClick\":1: in function <string>:\"*:OnClick\":1",
			["session"] = 6,
			["counter"] = 3,
		}, -- [2]
		{
			["message"] = "...\\SkeenCore3GUISpellFlash\\SkeenCore3GUISpellFlash-v1.1.4.lua:37: attempt to index upvalue \"GUI\" (a nil value)",
			["time"] = "2013/09/20 11:34:46",
			["locals"] = "self = <table> {\n ActivateGUI = <func> @..\\SkeenCore3GUI.lua:41\n SetUpdateInterval = <func> @..\\SkeenCore3Options.lua:106\n GetScale = <func> @..\\SkeenCore3Options.lua:93\n options = SkeenCore3OptionFrame {}\n RegisterDisabledGUI = <func> @..\\SkeenCore3GUIDisabled.lua:6\n LoadModules = <func> @..\\SkeenCore3Modules.lua:79\n option_frame_name = \"SkeenCore3OptionFrame\"\n HandlePluginOptionsFrame = <func> @..\\SkeenCore3Modules.lua:22\n displayFrame = <unnamed> {}\n CreateOptionFrame = <func> @..\\SkeenCore3Options.lua:6\n PrepareSkeenCore3Database = <func> @..\\SkeenCore3.lua:47\n CreateSlashCommands = <func> @..\\SkeenCore3Slash.lua:11\n ProcessCooldowns = <func> @..\\SkeenCore3.lua:69\n UpdateActiveGUI = <func> @..\\SkeenCore3GUI.lua:29\n SetScale = <func> @..\\SkeenCore3Options.lua:97\n GetLocked = <func> @..\\SkeenCore3Options.lua:84\n RotationUpdate = <func> @..\\SkeenCore3.lua:95\n LoadGUIs = <func> @..\\SkeenCore3GUI.lua:70\n SlashCommandList = <func> @..\\SkeenCore3Slash.lua:60\n UpdateDragability = <func> @..\\SkeenCore3Frame.lua:25\n ToggleLocked = <func> @..\\SkeenCore3Options.lua:88\n GetUpdateInterval = <func> @..\\SkeenCore3Options.lua:102\n CreateGUI = <func> @..\\SkeenCore3Frame.lua:4\n events = <table> {}\n PrepareSkeenCore3Active = <func> @..\\SkeenCore3.lua:19\n UpdateActiveModule = <func> @..\\SkeenCore3Modules.lua:43\n HandleGUIOptionsFrame = <func> @..\\SkeenCore3GUI.lua:8\n GetFirstGUI = <func> @..\\SkeenCore3GUI.lua:85\n eventHandler = <unnamed> {}\n}\nGUIName = \"SkeenCore3GUISpellFlash\"\nSkeenCore3 = <table> {\n ActivateGUI = <func> @..\\SkeenCore3GUI.lua:41\n SetUpdateInterval = <func> @..\\SkeenCore3Options.lua:106\n GetScale = <func> @..\\SkeenCore3Options.lua:93\n options = SkeenCore3OptionFrame {}\n RegisterDisabledGUI = <func> @..\\SkeenCore3GUIDisabled.lua:6\n LoadModules = <func> @..\\SkeenCore3Modules.lua:79\n option_frame_name = \"SkeenCore3OptionFrame\"\n HandlePluginOptionsFrame = <func> @..\\SkeenCore3Modules.lua:22\n displayFrame = <unnamed> {}\n CreateOptionFrame = <func> @..\\SkeenCore3Options.lua:6\n PrepareSkeenCore3Database = <func> @..\\SkeenCore3.lua:47\n CreateSlashCommands = <func> @..\\SkeenCore3Slash.lua:11\n ProcessCooldowns = <func> @..\\SkeenCore3.lua:69\n UpdateActiveGUI = <func> @..\\SkeenCore3GUI.lua:29\n SetScale = <func> @..\\SkeenCore3Options.lua:97\n GetLocked = <func> @..\\SkeenCore3Options.lua:84\n RotationUpdate = <func> @..\\SkeenCore3.lua:95\n LoadGUIs = <func> @..\\SkeenCore3GUI.lua:70\n SlashCommandList = <func> @..\\SkeenCore3Slash.lua:60\n UpdateDragability = <func> @..\\SkeenCore3Frame.lua:25\n ToggleLocked = <func> @Add",
			["stack"] = "...\\SkeenCore3GUISpellFlash\\SkeenCore3GUISpellFlash-v1.1.4.lua:37: in function \"RemoveGUI\"\nSkeenCore3-1.10.0.5\\SkeenCore3GUI.lua:45: in function \"ActivateGUI\"\nSkeenCore3-1.10.0.5\\SkeenCore3GUI.lua:31: in function \"UpdateActiveGUI\"\nSkeenCore3-1.10.0.5\\SkeenCore3Events.lua:24: in function \"?\"\nSkeenCore3-1.10.0.5\\SkeenCore3Events.lua:9: in function <SkeenCore3\\SkeenCore3Events.lua:9>",
			["session"] = 6,
			["counter"] = 2,
		}, -- [3]
		{
			["message"] = "[ADDON_ACTION_BLOCKED] AddOn \"LUI\" tried to call the protected function \"RaidMenu_Parent:SetPoint()\".",
			["time"] = "2013/09/20 11:58:22",
			["stack"] = "!BugGrabber-r193-release\\BugGrabber.lua:587: in function <!BugGrabber\\BugGrabber.lua:587>\n<in C code>\nLUI-v3.8.0-602\\modules\\raidmenu.lua:565: in function <LUI\\modules\\raidmenu.lua:555>",
			["session"] = 8,
			["counter"] = 22,
		}, -- [4]
		{
			["message"] = "Invalid Custom Control Type - Aura_EditBox",
			["time"] = "2013/09/20 13:56:59",
			["stack"] = "AceConfigDialog-3.0\\AceConfigDialog-3.0-58.lua:1588: in function \"FeedGroup\"\nAceConfigDialog-3.0\\AceConfigDialog-3.0-58.lua:1513: in function <AceConfigDialog-3.0\\AceConfigDialog-3.0.lua:1493>\n(tail call): ?\n<in C code>\n<string>:\"safecall Dispatcher[3]\":9: in function <string>:\"safecall Dispatcher[3]\":5\n(tail call): ?\nAce3-Release-r1098\\AceGUI-3.0\\AceGUI-3.0-33.lua:314: in function \"Fire\"\nAceGUI-3.0-33\\widgets\\AceGUIContainer-TreeGroup.lua:504: in function \"SetSelected\"\nAceGUI-3.0-33\\widgets\\AceGUIContainer-TreeGroup.lua:192: in function <AceGUI-3.0\\widgets\\AceGUIContainer-TreeGroup.lua:188>",
			["session"] = 16,
			["counter"] = 1,
		}, -- [5]
	},
}
